"""fase2: users.auth_id

Revision ID: 43160e8cdbc3
Revises: 5b847c703497
Create Date: 2026-10-02 23:39:38.160080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43160e8cdbc3'
down_revision: Union[str, Sequence[str], None] = '5b847c703497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_id', sa.UUID(), nullable=False))
    op.create_unique_constraint('uq_users_auth_id', 'users', ['auth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_auth_id', 'users', type_='unique')
    op.drop_column('users', 'auth_id')
    # ### end Alembic commands ###
